name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure user name and email
        run: |
          git config user.name "Sync-Bot"
          git config user.email "xchwarze@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Workspace
        run: |
          mkdir build
          cd build

      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: 'xchwarze/frieren'
          path: 'build/frieren'

      - name: Checkout modules repository
        uses: actions/checkout@v4
        with:
          repository: 'xchwarze/frieren-modules'
          path: 'build/frieren-modules'

      - name: Build each module
        run: |
          for dir in build/frieren-modules/*; do
            if [ -d "$dir" ]; then
              echo -e "\n\n\n-------------------------"
              echo "[*] Processing directory $dir"
              cd "$dir"

              echo "[*] Prepare project"
              yarn install --frozen-lockfile
              cp config/.env.release .env
              echo "VITE_COMMON_ALIAS='../../frieren/frieren-front/src'" >> .env

              echo "[*] Build module"
              yarn build
              
              echo "[*] Generate module package"
              rm -f dist/*.js dist/*.css dist/*.svg
              find dist -type f -name "*.sh" -exec chmod +x {} \;
              mv dist "${dir##*/}"
              tar -czf "${dir##*/}".tar.gz "${dir##*/}"
              mv "${dir##*/}".tar.gz ../../../modules
              cd -
            fi
          done

      - name: Commit and push changes
        run: |
          cd ..
          git config user.email "xchwarze@gmail.com"
          git config user.name "CI Bot"
          git add modules/*
          git commit -am "Add updated module packages"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/xchwarze/frieren-modules-release.git
          git push origin master
