name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Setup directories
        run: |
          mkdir -p ${{ github.workspace }}/build
          mkdir -p ${{ github.workspace }}/repo

      - name: Checkout current repo to /repo
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/repo
          fetch-depth: 0

      - name: Checkout main repository to /build/frieren
        uses: actions/checkout@v4
        with:
          repository: 'xchwarze/frieren'
          path: ${{ github.workspace }}/build/frieren
          persist-credentials: false

      - name: Checkout modules repository to /build/frieren-modules
        uses: actions/checkout@v4
        with:
          repository: 'xchwarze/frieren-modules'
          path: ${{ github.workspace }}/build/frieren-modules
          persist-credentials: false

      - name: Build each module
        run: |
          for dir in ${{ github.workspace }}/build/frieren-modules/*; do
            if [ -d "$dir" ]; then
              echo "[*] Processing directory: $dir"
              cd "$dir"

              echo "[*] Prepare project"
              yarn install --frozen-lockfile
              cp config/.env.release .env
              echo "VITE_COMMON_ALIAS='${{ github.workspace }}/build/frieren/frieren-front/src'" >> .env

              echo "[*] Build library"
              yarn build
              
              echo "[*] Generate module package"
              rm -f dist/*.js dist/*.css dist/*.svg
              find dist -type f -name "*.sh" -exec chmod +x {} \;
              mv dist "${dir##*/}"

              echo "[*] Tag and save version"
              VERSION=$(jq -r '.version' package.json)
              tar -czf "${dir##*/}-$VERSION.tar.gz" "${dir##*/}"
              mv "${dir##*/}-$VERSION.tar.gz" ${{ github.workspace }}/repo/modules

              cd -
            fi
          done

      - name: Setup and run release script
        run: |
          cd ${{ github.workspace }}/repo/bin
          yarn install --frozen-lockfile
          yarn release --source ${{ github.workspace }}/build/frieren-modules --build ${{ github.workspace }}/repo/modules

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}/repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add json/* modules/*
          git commit -m "Regenerate module packages"
          git push
